# Generated by Django 6.1 on 2026-08-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_alter_specialization_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialization',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='specialization',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='medicalsystem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='medicalsystem',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='specialization',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='medical_system',
        ),
    ]
