# Generated by Django 6.1 on 2026-08-14 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('category', models.CharField(choices=[('cbc', 'CBC'), ('rbs', 'RBS'), ('bp', 'Blood Pressure'), ('lipid', 'Lipid Profile'), ('other', 'Other Clinical')], max_length=20)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('reference_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reference_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gender_specific', models.BooleanField(default=False)),
                ('male_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('male_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('female_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('female_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BulkImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(max_length=50)),
                ('file_name', models.CharField(max_length=255)),
                ('total_records', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error_report', models.FileField(blank=True, null=True, upload_to='imports/errors/')),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthCheckup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkup_date', models.DateField(db_index=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_demo', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_checkups', to='doctors.doctor')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checkups', to='patients.patient')),
            ],
            options={
                'ordering': ['-checkup_date'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalParameterValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('normal', 'Within Reference Range'), ('abnormal', 'Outside Configured Reference Range'), ('unknown', 'Unknown / Not Evaluated')], default='unknown', max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=300)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='health_records.clinicalparameter')),
                ('health_checkup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_values', to='health_records.healthcheckup')),
            ],
            options={
                'ordering': ['parameter__display_order'],
            },
        ),
        migrations.CreateModel(
            name='CBCReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hemoglobin', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rbc_count', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('wbc_count', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('platelet_count', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True)),
                ('hematocrit', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('mcv', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('mch', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('mchc', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rdw', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('neutrophils', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('lymphocytes', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('monocytes', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('eosinophils', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('basophils', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('health_checkup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cbc_report', to='health_records.healthcheckup')),
            ],
        ),
        migrations.CreateModel(
            name='BloodPressureReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systolic', models.PositiveSmallIntegerField()),
                ('diastolic', models.PositiveSmallIntegerField()),
                ('pulse_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=30)),
                ('measured_at', models.DateTimeField()),
                ('remarks', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('health_checkup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bp_reports', to='health_records.healthcheckup')),
            ],
            options={
                'ordering': ['-measured_at'],
            },
        ),
        migrations.CreateModel(
            name='LipidProfileReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cholesterol', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('hdl', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ldl', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('triglycerides', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('vldl', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cholesterol_hdl_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('health_checkup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lipid_report', to='health_records.healthcheckup')),
            ],
        ),
        migrations.CreateModel(
            name='RBSReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unit', models.CharField(default='mg/dL', max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('health_checkup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rbs_report', to='health_records.healthcheckup')),
            ],
        ),
        migrations.AddIndex(
            model_name='healthcheckup',
            index=models.Index(fields=['patient', 'checkup_date'], name='health_reco_patient_8c4525_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clinicalparametervalue',
            unique_together={('health_checkup', 'parameter')},
        ),
    ]
