# Generated by Django 6.1 on 2026-08-14 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=30)),
                ('action', models.CharField(db_index=True, max_length=50)),
                ('module', models.CharField(db_index=True, max_length=50)),
                ('record_id', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(default='success', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['module', 'action'], name='audit_audit_module_365bd8_idx'), models.Index(fields=['user', 'timestamp'], name='audit_audit_user_id_e8be02_idx')],
            },
        ),
    ]
