# Generated by Django 6.1 on 2026-08-14 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('category', models.CharField(choices=[('student', 'Student'), ('staff', 'University Staff'), ('staff_family', 'Staff Family Member')], db_index=True, max_length=20)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('mobile', models.CharField(blank=True, db_index=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('emergency_contact', models.CharField(blank=True, max_length=15)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(db_index=True, max_length=40, unique=True)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='masters.department')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='StaffFamilyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('Spouse', 'Spouse'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Father', 'Father'), ('Mother', 'Mother'), ('Other', 'Other authorized dependent')], max_length=30)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_profile', to='patients.patient')),
                ('related_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='patients.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_number', models.CharField(db_index=True, max_length=40, unique=True)),
                ('semester', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='masters.department')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='patients.patient')),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='masters.programme')),
            ],
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['name', 'mobile'], name='patients_pa_name_8a3122_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['category', 'status'], name='patients_pa_categor_58d22c_idx'),
        ),
    ]
