# Generated by Django 6.1 on 2026-08-14 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('masters', '0002_medicalsystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='medical_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='masters.medicalsystem'),
        ),
    ]
