# Generated by Django 6.1 on 2026-08-15 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_doctor_medical_system'),
        ('masters', '0006_alter_specialization_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='medical_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='masters.medicalsystem'),
        ),
    ]
